---
title: "EDA"
output: github_document
---
```{r, include=FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal()+theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_color_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r loading dataset}
weather_df = read_csv(file = "./data/weather_df.csv") %>%
  mutate(
    month = lubridate::floor_date(date, unit = "month")
  )
weather_df
```

## 'group_by'

```{r}
weather_df %>%
  group_by(name, month)
```

## counting things

count month observations

```{r}
weather_df %>%
  group_by (name, month) %>%
  summarize(n_obs = n())

```

we can use 'count()'

```{r}
weather_df %>%
  count(name, month, name = "n_obs")
```

**NEVER** use base R's 'table'

the professor hates this code and we should not use it
```{r}
weather_df %>%
  pull(month) %>%
  table()
```


other helpful counters
```{r}
weather_df%>%
  group_by(month)%>%
  summarize(
    n_obs=n(),
    n_days=n_distinct(date)
  )
```









